# Generated by Django 6.0.5 on 2026-06-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("language", "Programming Language"),
                    ("frontend", "Frontend"),
                    ("backend", "Backend"),
                    ("database", "Database"),
                    ("datascience", "Data Science"),
                    ("tools", "Tools & Platforms"),
                ],
                default="language",
                max_length=100,
            ),
        ),
    ]
